# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a3aa80f8455060fd0b57681c513b33afcac2e0fbc4c6b0de1ae7dc021d2c7f50c44e4da45998f87bfc77e63b96a0bfdcccf1115a36635f61c3d176d5235847e

test:
  secret_key_base: 918b10972b3b255bb0177753b6c55f29dee58133a2ba42b2773cf88a42355e26efed8cf07db758d3afaebd76008db333c64a7676d2613c0686bb2788c0c895b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
